### ISSUE TITLE
[TODO] Prepare v9

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1938]
Tracking list of changes for `v9`:

- [x] Drop support for `yarn`
- [x] Drop support for `node v7.9.0`
- [x] Drop support from `vscode` using `node v7.9.0`
- [x] Update dependencies
- [x] Use true `IoC` via `Inversify`
- [x] Do not show `Restart` messages for `vscode` versions that support icon theme reloading
- [x] Improve language resource manager to include a language as soon as it lands in our repo
- [x] Bundle the `nls` resources to a single file, wherever applicable
- [x] Mute console messages when running in `debug` mode
- [x] Show Error message if `vscode` version is not supported
- [x] Make all I/O operations asynchronous
- [x] Bundle application via `Webpack`
- [x] Add test case to prevent duplicate icon declarations without different `disabled` attribute
- [x] Implement application integrity check via `nsri`
- [x] Switch to new `CodeClimate` test reporter (`linux` and `osx` only)
- [x] Drop usage of `Codecov` test reporter
- [x] Improved project detection
- [x] Switch to new `vscode` typings (`@types/vscode`)
 
The above list is subjected to changes as we get along.

**Comment by JimiC** [comment]
@vscode-icons/development  If you want anything added to `v9` please let me know.

**Comment by jens1o** [comment]
Fits to me. :)

Thanks for your work!

**Comment by csvn** [comment]
> Do not show Restart messages for vscode versions that support icon theme reloading.

That will be awesome. Thanks for your work @JimiC!

> Implement application integrity check via nsri.

I did not find any issues with integrity checking (wanted to see if there was any progress 😉). Will this feature hash files and check for changes when the extension starts?

**Comment by JimiC** [comment]
>I did not find any issues with integrity checking (wanted to see if there was any progress 😉). Will this feature hash files and check for changes when the extension starts?

Yes, it's going to check against the hashed bundled file but `nsri` isn't ready yet. Still, have work to do on it and I'm kinda over my head at work.

**Comment by csvn** [comment]
> Still, have work to do on it and I'm kinda over my head at work.

Totally get that, no worries, I was just curious. I've dabbled a bit in open source, so I know how much time it can take.
